"use client";

import { useMemo, useState } from "react";

import { Pencil } from "lucide-react";

import type { IProfile, IProfileStats } from "@/app/features/profile/types";
import { formatJoinDate } from "@/app/features/profile/utils/formatJoinDate";
import { isAutoGeneratedNickname } from "@/app/features/profile/utils/isAutoGeneratedNickname";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

import { NicknameFallbackDialog } from "./NicknameFallbackDialog";
import { ProfileEditDialog } from "./ProfileEditDialog";

interface IProps {
  profile: IProfile;
  stats: IProfileStats;
  isMe: boolean;
}

/**
 * 닉네임에서 Avatar fallback 첫 글자를 안전하게 추출한다.
 * UserMenu와 동일한 패턴이지만 의존성을 만들지 않기 위해 본 컴포넌트에 로컬로 둔다.
 * @param nickname 사용자 닉네임 (null/빈 문자열 허용)
 * @return initial 항상 1글자 string ("?" fallback)
 */
function getAvatarInitial({ nickname }: { nickname: string | null }): {
  initial: string;
} {
  if (!nickname || nickname.length === 0) {
    return { initial: "?" };
  }

  return { initial: nickname.charAt(0).toUpperCase() };
}

/**
 * Step 3 프로필 PR (#18): 프로필 화면 본체 (client component).
 *
 * 구성:
 * - 헤더: Avatar + 닉네임 + 가입일
 * - bio: 일반 `<p>` 렌더 (dangerouslySetInnerHTML 금지 — XSS 가드)
 * - 누적 전적 그리드: 승/패/무/총
 * - 본인일 때만: "편집" 버튼 + ProfileEditDialog + (자동 닉네임이면) NicknameFallbackDialog
 *
 * 자동 닉네임 fallback 발화 조건:
 * - 본인 진입 (`isMe=true`)
 * - 닉네임이 `/^(Player|Anon)_[0-9a-f]{8}$/` 매치 (handle_new_user 트리거 출력 형식)
 * - 이전에 dismiss하지 않음 (localStorage 가드는 NicknameFallbackDialog 내부에서 처리)
 *
 * React 19 Compiler 가드:
 * - formatJoinDate는 외부 헬퍼라 안전.
 * - isAutoGeneratedNickname도 외부 헬퍼 — useMemo로 한 번 더 묶을 필요 없지만,
 *   props 변경 추적을 명확히 하기 위해 useMemo로 격리.
 */
export function ProfileView({ profile, stats, isMe }: IProps) {
  const [editOpen, setEditOpen] = useState(false);

  const { label: joinDateLabel } = useMemo(() => {
    return formatJoinDate({ isoString: profile.created_at });
  }, [profile.created_at]);

  const { isAuto } = useMemo(() => {
    return isAutoGeneratedNickname({ value: profile.nickname });
  }, [profile.nickname]);

  const { initial } = getAvatarInitial({ nickname: profile.nickname });

  const showFallbackDialog = isMe && isAuto;

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 p-4 sm:p-6">
      {/* 헤더: Avatar + 닉네임 + 가입일 + 본인이면 편집 버튼 */}
      <Card>
        <CardContent className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex items-start gap-4">
            <Avatar size="lg">
              {profile.avatar_url ? (
                <AvatarImage
                  src={profile.avatar_url}
                  alt={profile.nickname ?? "user"}
                />
              ) : null}
              <AvatarFallback>{initial}</AvatarFallback>
            </Avatar>

            <div className="flex flex-col gap-1">
              <h1 className="font-heading text-xl font-medium leading-tight">
                {profile.nickname}
              </h1>
              {joinDateLabel ? (
                <p className="text-xs text-muted-foreground">
                  {joinDateLabel} 가입
                </p>
              ) : null}
            </div>
          </div>

          {isMe ? (
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => setEditOpen(true)}
              className="gap-1.5 self-start"
            >
              <Pencil className="size-4" aria-hidden="true" />
              <span>편집</span>
            </Button>
          ) : null}
        </CardContent>
      </Card>

      {/* bio — 일반 <p> 렌더로 XSS 가드. 빈 값이면 placeholder. */}
      <Card>
        <CardContent>
          {profile.bio ? (
            <p className="whitespace-pre-wrap text-sm leading-relaxed">
              {profile.bio}
            </p>
          ) : (
            <p className="text-sm text-muted-foreground">
              {isMe
                ? "한 줄 소개를 추가해보세요."
                : "아직 한 줄 소개가 없어요."}
            </p>
          )}
        </CardContent>
      </Card>

      {/* 누적 전적: get_profile_stats RPC가 RLS 우회해서 채워준 값 */}
      <Card>
        <CardContent>
          <h2 className="mb-3 font-heading text-base font-medium">누적 전적</h2>
          <div className="grid grid-cols-4 gap-3">
            <StatItem label="승" value={stats.wins} highlight />
            <StatItem label="패" value={stats.losses} />
            <StatItem label="무" value={stats.draws} />
            <StatItem label="총" value={stats.totalFinished} muted />
          </div>
        </CardContent>
      </Card>

      {/* 본인일 때만 편집 Dialog + 자동 닉네임 fallback 안내 */}
      {isMe ? (
        <ProfileEditDialog
          profile={profile}
          open={editOpen}
          onOpenChange={setEditOpen}
        />
      ) : null}

      {showFallbackDialog ? (
        <NicknameFallbackDialog
          userId={profile.id}
          onOpenEdit={() => setEditOpen(true)}
        />
      ) : null}
    </div>
  );
}

interface IStatItemProps {
  label: string;
  value: number;
  highlight?: boolean;
  muted?: boolean;
}

/**
 * 전적 그리드의 셀 컴포넌트. label + 큰 숫자.
 * highlight=true (승) → primary 색, muted=true (총) → muted-foreground.
 */
function StatItem({ label, value, highlight, muted }: IStatItemProps) {
  const valueClassName = highlight
    ? "text-primary"
    : muted
      ? "text-muted-foreground"
      : "text-foreground";

  return (
    <div className="flex flex-col items-center gap-1 rounded-lg bg-muted/40 py-3">
      <span className="text-xs text-muted-foreground">{label}</span>
      <span
        className={`font-heading text-xl font-medium leading-none ${valueClassName}`}
      >
        {value}
      </span>
    </div>
  );
}
