/**
 * Step 3 프로필 PR (#18): 닉네임이 handle_new_user 트리거가 자동 부여한 형식인지 판정.
 * 트리거는 `Player_<8hex>` 또는 `Anon_<8hex>` 형태로 닉네임을 생성한다
 * (`substring(uuid::text, 1, 8)`이므로 항상 8자 hex).
 * 이 판정 결과가 true이면서 사용자가 dismiss하지 않았을 때만 NicknameFallbackDialog를 발화시킨다.
 *
 * 정규식을 엄밀하게 잡은 이유: 사용자가 직접 `Player_abcd1234` 같은 닉네임을 의도적으로 골랐을
 * 가능성을 막기 위해 prefix + 정확히 8자 hex + 끝(`$`)을 모두 강제한다.
 */
const AUTO_NICKNAME_PATTERN = /^(Player|Anon)_[0-9a-f]{8}$/;

/**
 * 닉네임이 자동 생성된 fallback 형태인지 판정한다.
 * @param value 검사 대상 닉네임 (null/undefined 허용)
 * @return isAuto 자동 생성 형식이면 true
 */
export function isAutoGeneratedNickname({
  value,
}: {
  value: string | null | undefined;
}): { isAuto: boolean } {
  if (!value) {
    return { isAuto: false };
  }

  return { isAuto: AUTO_NICKNAME_PATTERN.test(value) };
}
